services:
    Sk\MathBundle\Controller\MathController:
        autoconfigure: true

    math_service:
        class:    '@SkMathBundle\Service\MathService'
        autowire: true

    SkMathBundle\Interfaces\MathLibInterface: '@math_service'
