services:
    Sk\MathBundle\Controller\MathController:
        autoconfigure: true

    math_service:
        class:    'Sk\MathBundle\Service\MathService'
        autowire: true

    Sk\MathBundle\Interfaces\MathLibInterface: '@math_service'
